---
when:
  - event: push
    branch: master
  - event: pull_request

matrix:
  nvim_version:
    - latest
    - 0.10
    - 0.11

steps:
  - name: test
    image: codeberg.org/mfussenegger/nvimdev:${nvim_version}
    pull: true
    commands:
      - apk add python3
      - luacheck .
      - busted
