-- Keep netrw on its default configuration.
--
-- This module intentionally leaves netrw untouched so that Neovim's
-- built-in settings provide the basic file browser experience without
-- any custom behavior.
